import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/src/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <head>
        {/* This is to prevent the page from flashing when the theme comes in */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
            try {
              if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                document.documentElement.classList.add('dark')
              } else {
                document.documentElement.classList.remove('dark')
              }
            } catch (_) {}
          `,
          }}
        />
      </head>
      <body className={inter.className}>
        <div className='bg-white dark:bg-black text-black dark:text-white transition-colors'>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
